sift-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 32
    space: "l2"
  build:
    nsubvec: [8]
    nbit: [8]
    nlist: [256]
  search:
    - topk: 100
      nrerank: [100,200]
    - topk: 10
      nrerank: [10,20]
  