# Configuration for RaBitQ (Randomized Bit Quantization)
# Current C++ backend only supports 128-D and 960-D vectors.

sift-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 16
    space: "l2"
  build:
    nlist: [256]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [200, 300, 500, 800, 1000]

gist-960-euclidean:
  common:
    data_bytes: 4
    ndim: 960
    nthread: 16
    space: "l2"
  build:
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [200, 300, 500, 800, 1000]

audio-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 16
    space: "l2"
  build:
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [200, 300, 500, 800, 1000]

siftsmall-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 16
    space: "l2"
  build:
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [200, 300, 500, 800, 1000]
