sift-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]

gist-960-euclidean:
  common:
    data_bytes: 4
    ndim: 960
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]

audio-128-euclidean:
  common:
    data_bytes: 4
    ndim: 128
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]

video-1024-euclidean:
  common:
    data_bytes: 4
    ndim: 1024
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]

text2image-200-euclidean:
  common:
    data_bytes: 4
    ndim: 200
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]

paper-200-euclidean:
  common:
    data_bytes: 4
    ndim: 200
    nthread: 16
    space: "l2"
  build:
    nbit: [2, 3, 4, 6, 8]
    nlist: [4096]
  search:
    - topk: 100
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [100]
    - topk: 10
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [10]
    - topk: 50
      nprobe: [10, 20, 30, 40, 50, 75, 100]
      nrerank: [50]
